controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

joint_state_broadcaster:
  ros__parameters: {}

mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: mecanum_lf_joint
    front_right_wheel_command_joint_name: mecanum_rf_joint
    rear_left_wheel_command_joint_name: mecanum_lb_joint
    rear_right_wheel_command_joint_name: mecanum_rb_joint
    
    kinematics:
        base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
        wheels_radius: 0.030
        sum_of_robot_center_projection_on_X_Y_axis: 0.219
    
    base_frame_id: base_footprint
    odom_frame_id: odom
    
    enable_odom_tf: true
    publish_ackermann_command: false
